# Generated by Django 4.1.7 on 2023-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tituto", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=200)),
                ("imagen", models.ImageField(upload_to="homepage/images/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
