# Generated by Django 4.1.7 on 2023-03-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.IntegerField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('NIT', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='tituto',
            new_name='titulo',
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_representante', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_perfil', models.ImageField(upload_to='Emprendedor/img_perfil/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('imagen_perfil', models.ImageField(upload_to='Consumidor/img_perfil/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.usuario')),
            ],
        ),
    ]
